leftnav:
- identifier: 8f0a8ee4-7455-0b1d-3aa0-9222b014ca8a
  name: Syllabus
  url: /pages/syllabus
  weight: 10
- identifier: external-212c526ddc804211823ac37d729650b6
  name: I. Electronic Materials and Devices
  url: https://openlearninglibrary.mit.edu/courses/course-v1:MITX+3.15.1x+2T2017/about
  weight: 1000
- identifier: external-faec9100afd24f5faf33a508eb6497ce
  name: II. Optical Materials and Devices
  url: https://openlearninglibrary.mit.edu/courses/course-v1:MITx+3.15.2x+2T2017/about
  weight: 1010
- identifier: external-f26b1f8e3bb74bedabda7e91aa93fc98
  name: III. Magnetic Materials and Devices
  url: https://openlearninglibrary.mit.edu/courses/course-v1:MITx+3.15.3x+2T2017/about
  weight: 1020
